CREATE TABLE Usuario (
id INT(6) AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
usuario VARCHAR(30) NOT NULL,
senha VARCHAR(20),
);

CREATE TABLE Categorias (
id INT(6) AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
);

CREATE TABLE Fornecedores (
id INT(6) AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
);

CREATE TABLE Produtos (
id INT(6) AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
);